change to return total_R_factor in minimization functions Without this parameters I had errors: Traceback (most recent call last):   File "./main_CoO_no_Au_S1614.py", line 142, in <module>     startCalculation()   File "./main_CoO_no_Au_S1614.py", line 122, in startCalculation     result = basinhopping(fun, x0, niter=200, take_step=take_step, minimizer_kwargs=minimizer_kwargs)   File "/home/yugin/anaconda3/lib/python3.5/site-packages/scipy/optimize/_basinhopping.py", line 605, in basinhopping     accept_tests, disp=disp)   File "/home/yugin/anaconda3/lib/python3.5/site-packages/scipy/optimize/_basinhopping.py", line 73, in __init__     minres = minimizer(self.x)   File "/home/yugin/anaconda3/lib/python3.5/site-packages/scipy/optimize/_basinhopping.py", line 273, in __call__     return self.minimizer(self.func, x0, **self.kwargs)   File "/home/yugin/anaconda3/lib/python3.5/site-packages/scipy/optimize/_minimize.py", line 450, in minimize     callback=callback, **options)   File "/home/yugin/anaconda3/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 328, in _minimize_lbfgsb     f, g = func_and_grad(x)   File "/home/yugin/anaconda3/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 274, in func_and_grad     g = _approx_fprime_helper(x, fun, epsilon, args=args, f0=f)   File "/home/yugin/anaconda3/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 628, in _approx_fprime_helper     grad[k] = (f(*((xk + d,) + args)) - f0) / d[k] TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'
and

Traceback (most recent call last):
  File "./main_CoO_no_Au_S1614.py", line 142, in <module>
    startCalculation()
  File "./main_CoO_no_Au_S1614.py", line 122, in startCalculation
    result = basinhopping(fun, x0, niter=200, take_step=take_step, minimizer_kwargs=minimizer_kwargs)
  File "/home/yugin/anaconda3/lib/python3.5/site-packages/scipy/optimize/_basinhopping.py", line 605, in basinhopping
    accept_tests, disp=disp)
  File "/home/yugin/anaconda3/lib/python3.5/site-packages/scipy/optimize/_basinhopping.py", line 73, in __init__
    minres = minimizer(self.x)
  File "/home/yugin/anaconda3/lib/python3.5/site-packages/scipy/optimize/_basinhopping.py", line 273, in __call__
    return self.minimizer(self.func, x0, **self.kwargs)
  File "/home/yugin/anaconda3/lib/python3.5/site-packages/scipy/optimize/_minimize.py", line 450, in minimize
    callback=callback, **options)
  File "/home/yugin/anaconda3/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 328, in _minimize_lbfgsb
    f, g = func_and_grad(x)
  File "/home/yugin/anaconda3/lib/python3.5/site-packages/scipy/optimize/lbfgsb.py", line 274, in func_and_grad
    g = _approx_fprime_helper(x, fun, epsilon, args=args, f0=f)
  File "/home/yugin/anaconda3/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 628, in _approx_fprime_helper
    grad[k] = (f(*((xk + d,) + args)) - f0) / d[k]
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'